Update js-api-specification.md
nhsconnect/nhsapp-developer-documentation pull request #23
Opened 2021-12-03 11:42 UTC by jack-kainos

NHSO-17847

JS API new function to allow url in whitelisted domain to open in browser overlay. Documentation update.

2022-01-10 14:01 UTC, spdevlin requested changes

2022-01-10 14:01 UTC, spdevlin commented on src/js-api-specification.md
> +nhsapp.navigation.openBrowserOverlay(https://www.nhs.uk/)
Missing quotes around the url

2022-01-11 08:25 UTC, jack-kainos commented on src/js-api-specification.md
> +nhsapp.navigation.openBrowserOverlay(https://www.nhs.uk/)
Url example updated

2022-01-11 16:17 UTC, spdevlin approved these changes

2022-01-11 16:17 UTC, merged